[package]
name = "phase2"
version = "0.2.3"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "Library for performing MPCs for creating zk-SNARK public parameters"
documentation = "https://docs.rs/phase2"
homepage = "https://github.com/ebfull/phase2"
license = "MIT/Apache-2.0"
repository = "https://github.com/ebfull/phase2"

[dependencies]
rand = "0.4"
byteorder = "1"
num_cpus = "1"
crossbeam = "0.7"
ff = "0.4.0"
blake2b_simd = "0.4.1"

[dependencies.bellman]
git = "https://github.com/filecoin-project/bellman"
branch = "master"

[dependencies.pairing]
git = "https://github.com/filecoin-project/pairing"
branch = "master"
